# jenkins-casc.yaml

jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
        # create a user called admin
        - id: "admin"
          password: "admin"
  authorizationStrategy: loggedInUsersCanDoAnything
unclassified:
  location:
    url: http://${SERVER_IP}:8080/
jobs:
  - script: >
      pipelineJob('upload-to-s3') {
        parameters {
          stringParam('bucket', '', 's3 Bucket to host static site.')
        }
        description('A job to download a git repository. Then upload files to Amazon S3')
        definition {
          cpsScm {
            scm {
              git {
                remote {url('https://github.com/alanredfordhayes/blog.git')}
                branch('*/master')
                scriptPath('docker/uploadToS3/Jenkinsfile')
              }
            }
            lightweight()
          }
        }
      }