pipeline {
  agent {
    docker { 
        image 'redhat/ubi8-minimal:latest'
        args '--privileged'       
    }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}