FROM python:3.9.16-slim-buster

LABEL version=0.1

USER root

COPY requirements.txt /root/dev/requirements.txt

COPY uploadToS3.py /root/dev/uploadToS3.py

WORKDIR /root/dev

RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy git

RUN pip3 install -r requirements.txt