pipeline {
  agent none
  stages {
    stage('upload-to-s3') {
      agent {
        docker { 
          image 'alanredfordhayes/upload-to-s3:latest'
          args "--privileged -v $HOME/.aws/credentials:/root/.aws/credentials:ro"
        }
      }
      steps {
        sh "python3 /root/dev/uploadToS3.py  --path site --bucket $bucket"
      }
    }
  }
}